import { db, usersTable, petsTable, adoptionRequestsTable, fosterRequestsTable, donationsTable, galleryPostsTable, lostFoundReportsTable } from "@workspace/db";

const UNSPLASH_DOGS = [
  "https://images.unsplash.com/photo-1552053831-71594a27632d?w=600",
  "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600",
  "https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=600",
  "https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=600",
  "https://images.unsplash.com/photo-1477884213360-7e9d7dcc1e48?w=600",
  "https://images.unsplash.com/photo-1534361960057-19f4434a4f5f?w=600",
];

const UNSPLASH_CATS = [
  "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600",
  "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=600",
  "https://images.unsplash.com/photo-1548247416-ec66f4900b2e?w=600",
  "https://images.unsplash.com/photo-1529778873920-4da4926a72c2?w=600",
  "https://images.unsplash.com/photo-1495360010541-f48722b34f7d?w=600",
];

const UNSPLASH_OTHER = [
  "https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=600",
  "https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?w=600",
  "https://images.unsplash.com/photo-1526515579900-98518e7862cc?w=600",
];

async function seed() {
  console.log("🌱 Seeding database...");

  // Clear existing data
  await db.delete(lostFoundReportsTable);
  await db.delete(galleryPostsTable);
  await db.delete(donationsTable);
  await db.delete(fosterRequestsTable);
  await db.delete(adoptionRequestsTable);
  await db.delete(petsTable);
  await db.delete(usersTable);

  // Create users
  const [admin, user1, user2] = await db.insert(usersTable).values([
    {
      fullName: "Admin Tabanni",
      email: "admin@tabbani.com",
      phone: "+962799000001",
      country: "Jordan",
      city: "Amman",
      role: "admin",
    },
    {
      fullName: "Sara Ahmed",
      email: "sara@example.com",
      phone: "+962799000002",
      country: "Jordan",
      city: "Amman",
      role: "user",
    },
    {
      fullName: "Omar Hassan",
      email: "omar@example.com",
      phone: "+962799000003",
      country: "Jordan",
      city: "Irbid",
      role: "user",
    },
  ]).returning();

  console.log("✅ Created 3 users");

  // Create pets
  const petsData = [
    {
      name: "Olive",
      type: "cat" as const,
      breed: "Tabby",
      gender: "female" as const,
      ageMonths: 11,
      weightKg: "3.5",
      size: "small" as const,
      color: "Gray & Brown",
      sterilized: true,
      yearlyVaccines: true,
      birthday: "2024-03-15",
      city: "Amman",
      status: "available" as const,
      purpose: "adopt" as const,
      imageUrls: [UNSPLASH_CATS[0], UNSPLASH_CATS[1]],
      story: "Hi there! I'm Olive. You might think I'm just an average cat, but once you meet me, you'll see there's much more to me than meets the eye! I'm smart, intuitive, and love affection—but I'll also spoil you with purrs, love, and endless cuddles. I'm playful, fun, and full of personality! I was born in late 2023. I can't wait to find my forever home! Could it be with you?",
      ownerId: user1.id,
      approved: true,
      featured: true,
    },
    {
      name: "Sanger",
      type: "dog" as const,
      breed: "Golden Retriever",
      gender: "male" as const,
      ageMonths: 36,
      weightKg: "30",
      size: "large" as const,
      color: "Golden",
      sterilized: true,
      yearlyVaccines: true,
      birthday: "2022-01-10",
      city: "Amman",
      status: "available" as const,
      purpose: "both" as const,
      imageUrls: [UNSPLASH_DOGS[0], UNSPLASH_DOGS[1]],
      story: "I'm Sanger, a joyful Golden Retriever who loves everyone I meet! I'm great with kids and other dogs. I've been trained and I know my basic commands. I'd love a family with a yard where I can run around.",
      ownerId: user2.id,
      approved: true,
      featured: true,
    },
    {
      name: "Max",
      type: "dog" as const,
      breed: "German Shepherd",
      gender: "male" as const,
      ageMonths: 24,
      weightKg: "28",
      size: "large" as const,
      color: "Black & Tan",
      sterilized: false,
      yearlyVaccines: true,
      birthday: "2023-01-01",
      city: "Irbid",
      status: "available" as const,
      purpose: "adopt" as const,
      imageUrls: [UNSPLASH_DOGS[2]],
      story: "Max is a loyal and intelligent German Shepherd looking for an experienced dog owner. He's protective and loving once he trusts you.",
      ownerId: user1.id,
      approved: true,
      featured: false,
    },
    {
      name: "Luna",
      type: "cat" as const,
      breed: "Persian",
      gender: "female" as const,
      ageMonths: 18,
      weightKg: "4",
      size: "medium" as const,
      color: "White",
      sterilized: true,
      yearlyVaccines: true,
      birthday: "2023-09-01",
      city: "Zarqa",
      status: "available" as const,
      purpose: "foster" as const,
      imageUrls: [UNSPLASH_CATS[2], UNSPLASH_CATS[3]],
      story: "Luna is a beautiful Persian cat who loves to be pampered. She's calm, gentle, and great with adults. She needs a quiet home where she can feel safe.",
      ownerId: user2.id,
      approved: true,
      featured: true,
    },
    {
      name: "Buddy",
      type: "dog" as const,
      breed: "Labrador",
      gender: "male" as const,
      ageMonths: 12,
      weightKg: "22",
      size: "large" as const,
      color: "Yellow",
      sterilized: false,
      yearlyVaccines: true,
      birthday: "2024-03-01",
      city: "Amman",
      status: "available" as const,
      purpose: "adopt" as const,
      imageUrls: [UNSPLASH_DOGS[3]],
      story: "Buddy is a young, energetic Labrador who loves to play fetch and swim. He's great with children and very social.",
      ownerId: user1.id,
      approved: true,
      featured: false,
    },
    {
      name: "Mimi",
      type: "cat" as const,
      breed: "Siamese",
      gender: "female" as const,
      ageMonths: 8,
      weightKg: "2.5",
      size: "small" as const,
      color: "Cream & Brown",
      sterilized: false,
      yearlyVaccines: false,
      birthday: "2024-07-01",
      city: "Amman",
      status: "available" as const,
      purpose: "both" as const,
      imageUrls: [UNSPLASH_CATS[4]],
      story: "Mimi is a talkative little Siamese kitten who loves attention. She's playful and will keep you entertained all day!",
      ownerId: user2.id,
      approved: true,
      featured: false,
    },
    {
      name: "Rex",
      type: "dog" as const,
      breed: "Rottweiler",
      gender: "male" as const,
      ageMonths: 48,
      weightKg: "40",
      size: "large" as const,
      color: "Black & Tan",
      sterilized: true,
      yearlyVaccines: true,
      birthday: "2021-01-01",
      city: "Irbid",
      status: "available" as const,
      purpose: "adopt" as const,
      imageUrls: [UNSPLASH_DOGS[4]],
      story: "Rex is a calm and well-trained Rottweiler who needs an experienced owner. He's loyal and protective but gentle with his family.",
      ownerId: user1.id,
      approved: true,
      featured: false,
    },
    {
      name: "Cleo",
      type: "cat" as const,
      breed: "Maine Coon",
      gender: "female" as const,
      ageMonths: 30,
      weightKg: "6",
      size: "large" as const,
      color: "Brown Tabby",
      sterilized: true,
      yearlyVaccines: true,
      birthday: "2022-09-01",
      city: "Amman",
      status: "available" as const,
      purpose: "adopt" as const,
      imageUrls: [UNSPLASH_CATS[0]],
      story: "Cleo is a majestic Maine Coon with a heart of gold. She's gentle, fluffy, and gets along well with other cats.",
      ownerId: user2.id,
      approved: true,
      featured: true,
    },
    {
      name: "Rocky",
      type: "dog" as const,
      breed: "Husky",
      gender: "male" as const,
      ageMonths: 20,
      weightKg: "25",
      size: "large" as const,
      color: "Gray & White",
      sterilized: false,
      yearlyVaccines: true,
      birthday: "2023-07-01",
      city: "Zarqa",
      status: "available" as const,
      purpose: "foster" as const,
      imageUrls: [UNSPLASH_DOGS[5]],
      story: "Rocky is an energetic Husky who loves running and playing outdoors. He needs an active family and daily exercise.",
      ownerId: user1.id,
      approved: true,
      featured: false,
    },
    {
      name: "Fluffy",
      type: "rabbit" as const,
      breed: "Holland Lop",
      gender: "female" as const,
      ageMonths: 6,
      weightKg: "1.5",
      size: "small" as const,
      color: "White",
      sterilized: false,
      yearlyVaccines: false,
      birthday: "2024-09-01",
      city: "Amman",
      status: "available" as const,
      purpose: "adopt" as const,
      imageUrls: [UNSPLASH_OTHER[0]],
      story: "Fluffy is an adorable Holland Lop rabbit who loves to hop around and explore. She's gentle and great for families with older children.",
      ownerId: user2.id,
      approved: true,
      featured: false,
    },
    {
      name: "Bella",
      type: "dog" as const,
      breed: "Poodle",
      gender: "female" as const,
      ageMonths: 14,
      weightKg: "10",
      size: "medium" as const,
      color: "White",
      sterilized: true,
      yearlyVaccines: true,
      birthday: "2024-01-01",
      city: "Amman",
      status: "available" as const,
      purpose: "both" as const,
      imageUrls: [UNSPLASH_DOGS[1]],
      story: "Bella is a smart and hypoallergenic Poodle mix. She's been trained and knows several tricks. Great for people with allergies!",
      ownerId: user1.id,
      approved: true,
      featured: false,
    },
    {
      name: "Shadow",
      type: "cat" as const,
      breed: "Bombay",
      gender: "male" as const,
      ageMonths: 24,
      weightKg: "5",
      size: "medium" as const,
      color: "Black",
      sterilized: true,
      yearlyVaccines: true,
      birthday: "2023-03-01",
      city: "Irbid",
      status: "available" as const,
      purpose: "adopt" as const,
      imageUrls: [UNSPLASH_CATS[1]],
      story: "Shadow is a sleek, all-black cat with golden eyes. He's mysterious but incredibly affectionate once he gets comfortable with you.",
      ownerId: user2.id,
      approved: true,
      featured: false,
    },
    {
      name: "Charlie",
      type: "dog" as const,
      breed: "Beagle",
      gender: "male" as const,
      ageMonths: 18,
      weightKg: "12",
      size: "medium" as const,
      color: "Tri-color",
      sterilized: false,
      yearlyVaccines: true,
      birthday: "2023-09-01",
      city: "Amman",
      status: "available" as const,
      purpose: "adopt" as const,
      imageUrls: [UNSPLASH_DOGS[2]],
      story: "Charlie is a curious and friendly Beagle who loves to sniff and explore. He's great with children and other dogs.",
      ownerId: user1.id,
      approved: true,
      featured: false,
    },
    {
      name: "Nala",
      type: "cat" as const,
      breed: "Abyssinian",
      gender: "female" as const,
      ageMonths: 15,
      weightKg: "3",
      size: "small" as const,
      color: "Ticked Tabby",
      sterilized: true,
      yearlyVaccines: true,
      birthday: "2023-12-01",
      city: "Zarqa",
      status: "available" as const,
      purpose: "foster" as const,
      imageUrls: [UNSPLASH_CATS[3]],
      story: "Nala is an active and playful Abyssinian cat. She loves to climb, explore, and play with feather toys. She needs a home with lots of enrichment.",
      ownerId: user2.id,
      approved: true,
      featured: false,
    },
    {
      name: "Bruno",
      type: "dog" as const,
      breed: "Boxer",
      gender: "male" as const,
      ageMonths: 30,
      weightKg: "30",
      size: "large" as const,
      color: "Fawn & White",
      sterilized: true,
      yearlyVaccines: true,
      birthday: "2022-09-01",
      city: "Amman",
      status: "available" as const,
      purpose: "both" as const,
      imageUrls: [UNSPLASH_DOGS[3]],
      story: "Bruno is a playful and energetic Boxer who loves people. He's great with kids and makes an excellent family companion.",
      ownerId: user1.id,
      approved: false,
      featured: false,
    },
    {
      name: "Whiskers",
      type: "rabbit" as const,
      breed: "Angora",
      gender: "male" as const,
      ageMonths: 10,
      weightKg: "2",
      size: "small" as const,
      color: "Gray",
      sterilized: false,
      yearlyVaccines: false,
      birthday: "2024-05-01",
      city: "Irbid",
      status: "available" as const,
      purpose: "adopt" as const,
      imageUrls: [UNSPLASH_OTHER[1]],
      story: "Whiskers is a fluffy Angora rabbit with a gentle temperament. He loves to be groomed and petted.",
      ownerId: user2.id,
      approved: true,
      featured: false,
    },
    {
      name: "Daisy",
      type: "dog" as const,
      breed: "Bichon Frise",
      gender: "female" as const,
      ageMonths: 8,
      weightKg: "5",
      size: "small" as const,
      color: "White",
      sterilized: false,
      yearlyVaccines: true,
      birthday: "2024-07-15",
      city: "Amman",
      status: "available" as const,
      purpose: "adopt" as const,
      imageUrls: [UNSPLASH_DOGS[5]],
      story: "Daisy is a fluffy white Bichon Frise puppy full of love and energy. She's hypoallergenic and great for apartment living.",
      ownerId: user1.id,
      approved: true,
      featured: false,
    },
    {
      name: "Tiger",
      type: "cat" as const,
      breed: "Bengal",
      gender: "male" as const,
      ageMonths: 20,
      weightKg: "4.5",
      size: "medium" as const,
      color: "Spotted Brown",
      sterilized: true,
      yearlyVaccines: true,
      birthday: "2023-07-01",
      city: "Zarqa",
      status: "available" as const,
      purpose: "adopt" as const,
      imageUrls: [UNSPLASH_CATS[4]],
      story: "Tiger is a wild-looking Bengal cat with a loving personality. He loves interactive toys and playing fetch—yes, like a dog!",
      ownerId: user2.id,
      approved: true,
      featured: false,
    },
    {
      name: "Coconut",
      type: "rabbit" as const,
      breed: "Dutch",
      gender: "female" as const,
      ageMonths: 4,
      weightKg: "1.2",
      size: "small" as const,
      color: "Black & White",
      sterilized: false,
      yearlyVaccines: false,
      birthday: "2024-11-01",
      city: "Amman",
      status: "available" as const,
      purpose: "adopt" as const,
      imageUrls: [UNSPLASH_OTHER[2]],
      story: "Coconut is a tiny Dutch rabbit with a big personality. She's curious and loves to binky around her enclosure.",
      ownerId: user1.id,
      approved: true,
      featured: false,
    },
    {
      name: "Zeus",
      type: "dog" as const,
      breed: "Doberman",
      gender: "male" as const,
      ageMonths: 36,
      weightKg: "35",
      size: "large" as const,
      color: "Black & Rust",
      sterilized: true,
      yearlyVaccines: true,
      birthday: "2022-03-01",
      city: "Irbid",
      status: "available" as const,
      purpose: "adopt" as const,
      imageUrls: [UNSPLASH_DOGS[0]],
      story: "Zeus is a noble and intelligent Doberman who has been professionally trained. He's loyal and protective, perfect for a confident owner.",
      ownerId: user2.id,
      approved: true,
      featured: false,
    },
  ];

  const pets = await db.insert(petsTable).values(petsData).returning();
  console.log(`✅ Created ${pets.length} pets`);

  // Adoption requests
  await db.insert(adoptionRequestsTable).values([
    { petId: pets[0].id, requesterId: user2.id, message: "I'd love to adopt Olive! I have a quiet apartment and no other pets.", status: "pending" },
    { petId: pets[1].id, requesterId: user1.id, message: "Sanger looks wonderful. My family has a large yard and we have experience with big dogs.", status: "approved" },
    { petId: pets[2].id, requesterId: user2.id, message: "Max would be a great companion for me.", status: "pending" },
    { petId: pets[3].id, requesterId: user1.id, message: "Luna is perfect for my quiet lifestyle.", status: "rejected" },
    { petId: pets[4].id, requesterId: user2.id, message: "Buddy looks like so much fun! I run daily.", status: "pending" },
  ]);
  console.log("✅ Created 5 adoption requests");

  // Foster requests
  await db.insert(fosterRequestsTable).values([
    { petId: pets[5].id, requesterId: user1.id, message: "I can foster Mimi for a month while she finds her forever home.", status: "approved" },
    { petId: pets[8].id, requesterId: user2.id, message: "I'd love to foster Rocky. I go hiking every weekend.", status: "pending" },
    { petId: pets[6].id, requesterId: user1.id, message: "Rex seems calm and I have experience with large breeds.", status: "pending" },
    { petId: pets[13].id, requesterId: user2.id, message: "Nala would be great in my cat-friendly home.", status: "approved" },
    { petId: pets[3].id, requesterId: user1.id, message: "Luna is perfect for fostering.", status: "pending" },
  ]);
  console.log("✅ Created 5 foster requests");

  // Donations
  await db.insert(donationsTable).values([
    { donorName: "Angele Yu", donorPhone: "+962799111111", amount: "150", type: "monetary", paymentMethod: "Visa", frequency: "one_time" },
    { donorName: "Neil Sims", donorPhone: "+962799222222", amount: "200", type: "monetary", paymentMethod: "Mastercard", frequency: "monthly" },
    { donorName: "Laura Smith", donorPhone: "+962799333333", amount: "100", type: "monetary", paymentMethod: "PayPal", frequency: "one_time" },
    { donorName: "John Doe", donorPhone: "+962799444444", amount: "300", type: "monetary", paymentMethod: "Visa", frequency: "one_time" },
    { donorName: "Hana Khalil", donorPhone: "+962799555555", amount: "50", type: "monetary", paymentMethod: "Mastercard", frequency: "monthly" },
    { donorName: "Lara Nasser", donorPhone: "+962799666666", type: "supplies", donationTypeLabel: "Food", description: "High-quality dry food for puppies and kittens, 10kg bags", frequency: "one_time" },
    { donorName: "Ahmad Bakr", donorPhone: "+962799777777", type: "supplies", donationTypeLabel: "Blankets", description: "Washable fleece blankets, 5 pieces", frequency: "one_time" },
    { donorName: "Rima Jaber", donorPhone: "+962799888888", amount: "75", type: "monetary", paymentMethod: "Visa", frequency: "one_time", petId: pets[0].id },
    { donorName: "Tariq Mansour", donorPhone: "+962799999999", amount: "125", type: "monetary", paymentMethod: "Mastercard", frequency: "monthly" },
    { donorName: "Sara Al-Rashid", donorPhone: "+962799000010", type: "supplies", donationTypeLabel: "Toys", description: "Durable rubber chew toys and interactive puzzle toys", frequency: "one_time" },
  ]);
  console.log("✅ Created 10 donations");

  // Gallery posts
  await db.insert(galleryPostsTable).values([
    {
      title: "Buddy came into our lives",
      content: "Buddy came into our lives when we after losing our previous dog. We weren't ready to love again, but this golden boy changed everything. From the moment he walked in, our house felt like a home again. His tail never stops wagging and his love is unconditional. Adopting through Tabbani was the best decision we ever made. The process was smooth, the team was supportive, and most importantly, we found our perfect match.",
      imageUrl: UNSPLASH_DOGS[0],
      authorId: user1.id,
    },
    {
      title: "Luna healed our hearts",
      content: "After losing our cat of 15 years, we thought we'd never open our hearts again. Then we found Luna on Tabbani. She's a Persian princess who somehow knew exactly what we needed. She curls up next to us every evening, purring away the sadness. We're so grateful to the Tabbani team for connecting us with her.",
      imageUrl: UNSPLASH_CATS[0],
      authorId: user2.id,
    },
    {
      title: "Fostering Rocky changed our weekend routine",
      content: "We signed up to foster Rocky for just a couple of weeks. Three months later, we're still his family and we couldn't imagine life without him. Fostering is such a rewarding experience—you help an animal in need while giving yourself time to decide if it's the right fit. 100% recommend fostering through Tabbani!",
      imageUrl: UNSPLASH_DOGS[4],
      authorId: user1.id,
    },
    {
      title: "Mimi chose us",
      content: "They say cats choose their owners, and Mimi certainly chose us. From the first day, she jumped on my husband's lap and refused to move. It's been six months now and she still thinks his laptop keyboard is her throne. We're so glad we found her on Tabbani.",
      imageUrl: UNSPLASH_CATS[2],
      authorId: user2.id,
    },
    {
      title: "A week turned into forever",
      content: "I only planned to foster for a week... three months later, I was filling out adoption papers. Zeus was supposed to be a temporary arrangement, but he won over my heart and my two children. He's patient, gentle, and fiercely protective. Our family is complete.",
      imageUrl: UNSPLASH_DOGS[3],
      authorId: user1.id,
    },
  ]);
  console.log("✅ Created 5 gallery posts");

  // Lost & Found reports
  await db.insert(lostFoundReportsTable).values([
    {
      reportType: "lost",
      name: "Biscuit",
      type: "Dog",
      breed: "Maltese",
      gender: "male",
      color: "White",
      ageMonths: 24,
      size: "small",
      city: "Amman",
      imageUrls: [UNSPLASH_DOGS[1]],
      description: "Lost near 7th Circle. Has a red collar with a bone tag. Very friendly.",
      lostDate: "2025-02-20",
      reporterId: user1.id,
      reporterName: "Sara Ahmed",
      reporterPhone: "+962799000002",
    },
    {
      reportType: "found",
      name: "Unknown",
      type: "Cat",
      breed: "Mixed",
      gender: "female",
      color: "Orange & White",
      ageMonths: 12,
      size: "medium",
      city: "Amman",
      imageUrls: [UNSPLASH_CATS[4]],
      description: "Found near Al-Rabieh. Very friendly and seems to be domesticated. Has no collar.",
      foundDate: "2025-02-25",
      reporterName: "Omar Hassan",
      reporterPhone: "+962799000003",
    },
    {
      reportType: "lost",
      name: "Toby",
      type: "Dog",
      breed: "Dachshund",
      gender: "male",
      color: "Brown",
      ageMonths: 36,
      size: "small",
      city: "Irbid",
      imageUrls: [UNSPLASH_DOGS[2]],
      description: "Lost in Irbid university area. He has a blue collar. Responds to Toby.",
      lostDate: "2025-03-01",
      reporterName: "Ahmad Al-Zoubi",
      reporterPhone: "+962777123456",
    },
    {
      reportType: "found",
      name: "Unknown",
      type: "Cat",
      breed: "Siamese mix",
      gender: "female",
      color: "Cream",
      ageMonths: 8,
      size: "small",
      city: "Zarqa",
      imageUrls: [UNSPLASH_CATS[3]],
      description: "Found near Zarqa downtown. Kitten, about 6-8 months old. Very sweet.",
      foundDate: "2025-03-05",
      reporterName: "Hana Khalil",
      reporterPhone: "+962799555555",
    },
    {
      reportType: "lost",
      name: "Coco",
      type: "Rabbit",
      breed: "Holland Lop",
      gender: "female",
      color: "Gray",
      ageMonths: 6,
      size: "small",
      city: "Amman",
      imageUrls: [UNSPLASH_OTHER[0]],
      description: "Escaped from her enclosure in Abdoun. She's very small with floppy ears.",
      lostDate: "2025-03-10",
      reporterName: "Lara Nasser",
      reporterPhone: "+962799666666",
    },
  ]);
  console.log("✅ Created 5 lost/found reports");

  console.log("🎉 Seed complete!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});
